# Ruby のベースイメージを指定
FROM ruby:3.2.3

# 環境変数の設定
ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo
ENV RAILS_ENV=development

# 必要なパッケージのインストール
RUN apt-get update -qq \
  && apt-get install -y ca-certificates curl gnupg \
  && mkdir -p /etc/apt/keyrings \
  && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
  && NODE_MAJOR=20 \
  && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
  && wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  yarn \
  vim

# アプリケーションディレクトリの作成
WORKDIR /app

# Gemfileを先にコピー（キャッシュ効率化）
COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

# アプリケーションのコードをコピー
COPY . .

# 開発サーバーを起動
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
